language: android

android:
  components:
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew checkstyle build
